### ISSUE TITLE
Data.EitherR not found --- some dependency missing in bower.json?

### ISSUE THREAD

**Issue by metaleap** [paluh/purescript-jaws#1]
When I add this as a dep to a project (without using it yet), that project fails to `pulp build` with:

    * Building project in /home/rox/c/ps/test-pscorefn-src
    Error found:
    in module Data.Validation.Jaws.Coproduct
    at bower_components/purescript-jaws/src/Data/Validation/Jaws/Coproduct.purs line 7, column 1 - line 7, column 28
    
      Module Data.EitherR was not found.
      Make sure the source file exists, and that it has been provided as an input to the compiler.

Using the current `master` branch of `purs` (prints as 0.11.6 dev build). Or maybe a new bug in this latest `purs` not yet showing up with your `--version` of it?

**Comment by metaleap** [comment]
Well, after doing a manual `bower install purescript-errors` I could also build `purescript-jaws`. Wonder how this wasn't picked up from jaws `bower.json` because I can tell it's in there! Odd. Maybe should be moved from devDependencies to main deps? Anyway feel free to close =)

**Comment by paluh** [comment]
Yeah, it should be in main deps. I'm away till Sunday so I will fix it when I'm back. Please be aware that it is still alpha and I'm planning to cleanup http module. I'm also preparing full form validation lib based on this, but this is yet another story.

**Comment by paluh** [comment]
Thanks for report! Fixed.
